charset_train: 0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~
charset_test: 0123456789abcdefghijklmnopqrstuvwxyz
max_label_length: 25
batch_size: 384
lr: 0.0007
warmup_pct: 0.075
weight_decay: 0.0
img_size:
- 32
- 128
patch_size:
- 4
- 8
embed_dim: 384
enc_num_heads: 6
enc_mlp_ratio: 4
enc_depth: 12
dec_num_heads: 12
dec_mlp_ratio: 4
dec_depth: 1
perm_num: 6
perm_forward: true
perm_mirrored: true
decode_ar: true
refine_iters: 1
dropout: 0.1
name: parseq
