name: isaac_VLP
_target_: strhub.models.isaac_VLP.system.Isaac_VLP

# Data
patch_size: [ 4, 8 ]  # [ height, width ]

# Architecture
embed_dim: 384
enc_num_heads: 6
enc_mlp_ratio: 4
enc_depth: 12
dec_num_heads: 12
dec_mlp_ratio: 4
dec_depth: 1
ref_depth: 0
ref_loss_scale: 1
ref_iters: 1
dec_sampling : "" # identity, pd (proability distribution)
dec_sampling_temp : 1
ref_objective: "CLM" # identity, CLM
QK: [['V', 'L', 'P'], ['V', 'L', 'P'], ['V', 'L', 'P']]

# Training
lr: 7e-4
dropout: 0.1