name: isaac_PV_VF
_target_: strhub.models.isaac_PV_VF.system.Isaac_PV_VF

# Data
patch_size: [ 4, 8 ]  # [ height, width ]

# Architecture
embed_dim: 384
enc_num_heads: 6
enc_mlp_ratio: 4
enc_depth: 12
dec_num_heads: 12
dec_mlp_ratio: 4
dec_depth: 1

# Training
lr: 7e-4
dropout: 0.1