name: parseq_R
_target_: strhub.models.parseq_R.system.PARSeq_R

# Data
patch_size: [ 4, 8 ]  # [ height, width ]

# Architecture
embed_dim: 384
enc_num_heads: 6
enc_mlp_ratio: 4
enc_depth: 12
dec_num_heads: 12
dec_mlp_ratio: 4
dec_depth: 1
ref_depth: 1
ref_mode: 'LM' # LM, MLM, etc.
head_char_emb_tying: true

# Training
lr: 7e-4
dropout: 0.1
perm_num: 1
perm_forward: true
perm_mirrored: false

# Decoding mode (test)
decode_ar: true
ref_iters: 1
